apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-sock-shop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tfinardi/microservices-demo
    targetRevision: HEAD
    path: app
  destination: 
    server: https://kubernetes.default.svc
    namespace: sock-shop

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

